### ISSUE TITLE
Travis CI integration

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-python#21]
We've got tests.  Let's make a robot run them for us.

**Comment by mittonk** [comment]
@tomelm , you said you could flip the bits?

**Comment by tomelm** [comment]
Yep, but we need a `.travis.yml` file first.

**Comment by asottile** [comment]
eheh, I did the interesting bits in #23

**Comment by mittonk** [comment]
@tomelm : OK, we've got a `.travis.yml` config now.  Over to you!

**Comment by dinahshi** [comment]
@mittonk I believe we switched it on yesterday; you can see indicators at the top of the readme on the repo page. Thanks @tomelm!

**Comment by mittonk** [comment]
Ah, there it is.  Nice.
