### ISSUE TITLE
Support rating urls for businesses

### ISSUE THREAD

**Issue by watterso** [Yelp/yelp-python#27]
Reviews come in with the image url name `rating_image_url` whereas Business come in with `rating_img_url`.

**Comment by mittonk** [comment]
https://www.yelp.com/developers/documentation/v2/business uses `rating_img_url`, but `reviews.rating_image_url`.

I'm a fan of the clientlib sticking fairly close to the API here, and not developing much specialized terminology --- this feels like a bug on the actual API, not the clientlib.

**Comment by tomelm** [comment]
Agreed with @mittonk. Let's stick with the API

**Comment by dinahshi** [comment]
Agree that naming should be consistent on the actual API but this is a problem in the current clientlib as businesses and reviews instantiate the same kind of rating object which only looks for `rating_image_url`. Relevant line [here](https://github.com/Yelp/yelp-python/blob/master/yelp/obj/rating.py#L16).

**Comment by mittonk** [comment]
Ah, that's a more verbose description.  Thanks for clarifying.
