### ISSUE TITLE
Bump version for py3 support and add classifiers

### ISSUE THREAD

**Issue by asottile** [Yelp/yelp-python#29]
Here's some art:

https://github.com/pre-commit/pre-commit/blob/master/setup.py#L26

**Comment by mittonk** [comment]
@asottile : Could you say more about "py3 support"?

**Comment by asottile** [comment]
The tests pass under python 3 so I assume the library works as well.  You can document this by specifying classifiers in setup.py.  Quite a few things scrape the pypi metadata and having classifiers indicating language support are perhaps the most important ones.
