### ISSUE TITLE
Explore different ways to dynamically populate the Client class

### ISSUE THREAD

**Issue by dinahshi** [Yelp/yelp-python#33]
In #31, we introduced some metaprogramming to split the Client class into modules by endpoint. As raised in #32, using inspect may not be the best way to do this.

**Comment by asottile** [comment]
Some other points:
- Any way you program this is going to make tooling difficults (pydoc, sphinx, anything that does static analysis)
- It's going to be harder for maintainers and consumers to understand than normal attribute access

I think you could get a *similar* interface with way less magic by doing something simple like:

```python
class Client(object):
    def __init__(...):
        self.business = Business(self)
        self.phone = Phone(self)
        # etc.

# Which would get used like
client = Client(...)
business = client.business.get_by_id(...)
```

I still think that's a little overkill as well.

I'd actually be happiest with an api like this  (pure functions, doesn't have circular dependency)

```python
from yelp.endpoints import business

client = Client(...)
my_business = business.get_by_id(client, id='...')
```

**Comment by mittonk** [comment]
I'd vote for less magic here.

The hard part here seems to be (user code interacts with Client) and (client interacts with Yelp server), with several endpoints in the middle.

What about splitting the "Client" class into ThingYouUseDirectly and ThingThatTalksToYelp?  

(Naming could be perhaps "Client" and "LowLevelClient")
