### ISSUE TITLE
Sort out "develop" vs "master" branch

### ISSUE THREAD

**Issue by mittonk** [Yelp/yelp-python#36]
"master" is the default branch.

But, we've also got a "develop" branch.

Not clear which one we should be merging things into, and @watterso thinks #27 was merged only into develop and not master (default)...

**Comment by watterso** [comment]
out-of-band chat with @tomelm:
`develop` is where we put changes that are ready to push to `master`
`master` reflects what is hosted in pypi

[PaaSTA](https://github.com/Yelp/paasta/) has Travis CI auto-deploy to pypi, [details here](https://docs.travis-ci.com/user/deployment/pypi). I'm going to close this issue and open one to setup auto deployment from master to pypi via Travis.

**Comment by watterso** [comment]
Filed Issue #37

**Comment by mittonk** [comment]
Sounds like a very reasonable plan.  Thanks, @watterso .
