### ISSUE TITLE
Pre-requisites for "requirements.txt"?

### ISSUE THREAD

**Issue by jrs477** [Yelp/yelp-python#39]
I tried to follow your example on Github but have some very basic questions, coming from a novice background. 

I saved the file "requirements.txt" in a directory and then in the terminal tried to run:
`pip install -r requirements.txt`

The following message was returned: 
```
  Could not find a version that satisfies the requirement auth2==1.0 (from -r requirements.txt (line 1)) (from versions: )

No matching distribution found for auth2==1.0 (from -r requirements.txt (line 1))
```

What other basic steps would I need to take before running the "pip install" command?

Thanks very much for your help!

**Comment by mittonk** [comment]
(To others who find this: we're debugging over in https://github.com/Yelp/yelp-api/issues/107 .)
