### ISSUE TITLE
Help Constructing API Client

### ISSUE THREAD

**Issue by jrs477** [Yelp/yelp-python#41]
Hi,

I have followed the Yelp-python basics exactly but receive an error after entering

```
with open('config_secret.json') as cred:
    creds = json.load(cred)
    auth = Oauth1Authenticator(**creds)
    client = Client(auth)

params = {
    'term': 'food',
    'lang': 'fr'
}
>>> client.search('San Francisco', **params)
```

My terminal spits out
`TypeError: character mapping must return integer, None or unicode
`

My guess is that this has something to do with the unicode of my keys/tokens in my `config_secret.json`.

What would be the most efficient way to resolve this error? Thanks for your help.

**Note: my` config_secret.json` is not in a `.gitignore `file, so I revised `io.open()` to `open()`.

**Comment by watterso** [comment]
@jrs477 I assume this is the issue you mentioned over in [yelp-api #108](https://github.com/Yelp/yelp-api/issues/108) in [this comment](https://github.com/Yelp/yelp-api/issues/108#issuecomment-188678686)?

For those following along, I responded to this issue in [this comment](https://github.com/Yelp/yelp-api/issues/108#issuecomment-190479032), I will copy and paste my response below and close this out.

* `json.load()` loads the contents of a file object (containing JSON) into a python dictionary
* the `**creds` shorthand expands a dictionary into 'kwargs', short info on that [here](http://stackoverflow.com/questions/1769403/understanding-kwargs-in-python), more verbose explanation in the [official python docs](https://docs.python.org/2/tutorial/controlflow.html#keyword-arguments).

snippet from app.py:
```python
import json
...
from yelp.oauth1_authenticator import Oauth1Authenticator
...
with open('keys.json') as creds_file:
    creds = json.load(creds_file)
auth = Oauth1Authenticator(**creds)
```
(redacted) contents of keys.json:
```json
{
    "consumer_key": "REDACTED",
    "consumer_secret": "REDACTED",
    "token": "REDACTED",
    "token_secret": "REDACTED"
}
```
