### ISSUE TITLE
Add raw json response method

### ISSUE THREAD

**Issue by dreyco676** [Yelp/yelp-python#45]
Parsing the data into python objects is fine but can hide new fields that may be added to the API overtime. 

Providing raw json allows caching of data with additional fields and accessing them again at a later time.

**Comment by tomelm** [comment]
We'll be sure to add fields to the clientlib if we make any changes to the API over time.

Could you provide more information on what you're trying to cache?

**Comment by dreyco676** [comment]
That makes sense, I wasn't sure if the API team was managing the Clientlib as well or if that was another team. Sometimes they get out of sync.

I can see from the TOS I'm only supposed to cache ids so that's what I'll plan on doing. Feel free to close this issue.

**Comment by watterso** [comment]
Yup API team manages the clientlibs too :)
