### ISSUE TITLE
API Search business result is in different order from Yelp web search

### ISSUE THREAD

**Issue by dyr0916** [Yelp/yelp-python#55]
Example: 'Super Chicken' at zipcode 22182.

On yelp web search, the top result is a restaurant named 'Super Chicken' located in Vienna VA, 22182 with 311 reviews.

However, through API, the first result is a restaurant named 'Super Chicken' but with location in 4323 Kenilworth Ave', u'Bladensburg, MD 20710 with 20 reviews.

Could you please help me understand why this is the case?

Thanks!

**Comment by dan98765** [comment]
This repository is for the python clientlib for Yelp's Fusion API; Yelp has a separate repository dedicated to Yelp Fusion API as a whole where it would be better to open this issue: https://github.com/Yelp/yelp-fusion/issues

There are definitely differences in how search works on the www site from the API search that are tricky, and there are many answered and several open issues over there asking questions about it.
